### ISSUE TITLE
How to do subclustering the best?

### ISSUE THREAD

**Issue by vertesy** [vertesy/Seurat.multicore#4]
#### Do you have to re identify variable genes? 

- TLDR: unclear, probably start from scratch

it was asked [here](https://github.com/satijalab/seurat/issues/1883)

Side note:
> **Running FindVariableGenes() and RunPCA() again on the integrated dataset does not seem helpful to me because the limited feature space of 3000 is not changed.** The alternative would be to subset() the population of interest and **run the complete preprocessing including integration only on those cells again.** That enables to change the feature space.

#### How to re identify variable genes *on integrated data*? 

> We do not support the identification of variable features on integrated data. If you want to subset and recluster using a new set of variable genes, you need to switch the assay of the subsetted to the 'RNA' assay. [[source](https://github.com/satijalab/seurat/issues/1528)] 

→ → It was not done in the test I did.

**Comment by Jiumeizhu** [comment]
Dear Seurat team,
Thanks for the last version of Seurat, I'm having some problems with the subsetting and reclustering. . For the first clustering, that works pretty well, I'm using the tutorial of "Integrating stimulated vs. control PBMC datasets" to integrate 10 samples. But my problem starts with the subsetting and reclustering, I don't know how to properly calculate the genes to be used in the reclustering.

I'm using three approaches, but I'm not sure which one is the right one.

**#1 directly using integrate assay runPCA.** 
macropahge.integrated<-subset(skinsamples.integrated, subset =celltype=="10-Macrophage/Dendritic Cell")
DefaultAssay(macropahge) <- "integrated"
macropahge.integrated <- RunPCA(object = macropahge.integrated, verbose = FALSE)
macropahge.integrated <- RunUMAP(object = macropahge.integrated, dims = 1:30)

macropahge.integrated  <- FindNeighbors(macropahge.integrated, dims = 1:30, verbose = FALSE)
macropahge.integrated <- FindClusters(macropahge.integrated, verbose = FALSE,resolution = 2)

DimPlot(macropahge.integrated, reduction = "umap",group.by = "seurat_clusters",label = TRUE)
DimPlot(macropahge.integrated, reduction = "umap",group.by = "orig.ident",label = TRUE) 

**#2 extract original UMI matrix and SCtransform ,batch correction.**
DefaultAssay(macropahge) <- "RNA"

macropahge.list <- SplitObject(macropahge, split.by = "orig.ident")

for (i in 1:length(x = macropahge.list)){
  macropahge.list[[i]] <- SCTransform(object = macropahge.list[[i]],verbose = FALSE,return.only.var.genes = FALSE)}

macropahge.features <- SelectIntegrationFeatures(object.list = macropahge.list, nfeatures = 3000)
macropahge.list <- PrepSCTIntegration(object.list = macropahge.list, anchor.features = macropahge.features)

reference_dataset <- which(names(macropahge.list) == "SC33")

macropahge.anchors <- FindIntegrationAnchors(object.list = macropahge.list, normalization.method = "SCT", k.filter = 13,   k.score = 12,dims = 1:10, anchor.features = macropahge.features, reference = reference_dataset)

macropahge.integrated <- IntegrateData(anchorset = macropahge.anchors, normalization.method = "SCT",k.weight = 50)

macropahge.integrated <- RunPCA(object = macropahge.integrated, verbose = FALSE)
macropahge.integrated <- RunUMAP(object = macropahge.integrated, dims = 1:30)

macropahge.integrated  <- FindNeighbors(macropahge.integrated, dims = 1:30, verbose = FALSE)
macropahge.integrated <- FindClusters(macropahge.integrated, verbose = FALSE,resolution = 1.2)

DimPlot(macropahge, reduction = "umap",group.by = "seurat_clusters",label = TRUE) + NoLegend()
DimPlot(macropahge, reduction = "umap",group.by = "orig.ident",label = TRUE) 

In this approach, cells in some samples are very low, around 10 to 30 cells. So I set very low k.filter = 13 and k.score = 12.

**#3 Processing as a single sample. Don't consider the  batch effect.**
DefaultAssay(macropahge) <- "RNA"
macropahge <- NormalizeData(macropahge)
macropahge <- FindVariableFeatures(macropahge, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(macropahge)
macropahge  <- ScaleData(macropahge, features = all.genes)
macropahge <- RunPCA(macropahge, features = VariableFeatures(object = macropahge))
macropahge <- RunUMAP(macropahge, dims = 1:10)
macropahge <- FindNeighbors(macropahge, dims = 1:10)
macropahge <- FindClusters(macropahge, resolution = 0.8)

DimPlot(macropahge, reduction = "umap",group.by = "seurat_clusters",label = TRUE) + NoLegend()
DimPlot(macropahge, reduction = "umap",group.by = "orig.ident",label = TRUE) 

3 methods can work, but I am not sure which method is right.
looking forward to your help~

Thanks.

**Comment by WeiZhu1998** [comment]
> Dear Seurat team,
> Thanks for the last version of Seurat, I'm having some problems with the subsetting and reclustering. . For the first clustering, that works pretty well, I'm using the tutorial of "Integrating stimulated vs. control PBMC datasets" to integrate 10 samples. But my problem starts with the subsetting and reclustering, I don't know how to properly calculate the genes to be used in the reclustering.
> 
> I'm using three approaches, but I'm not sure which one is the right one.
> 
> **#1 directly using integrate assay runPCA.**
> macropahge.integrated<-subset(skinsamples.integrated, subset =celltype=="10-Macrophage/Dendritic Cell")
> DefaultAssay(macropahge) <- "integrated"
> macropahge.integrated <- RunPCA(object = macropahge.integrated, verbose = FALSE)
> macropahge.integrated <- RunUMAP(object = macropahge.integrated, dims = 1:30)
> 
> macropahge.integrated <- FindNeighbors(macropahge.integrated, dims = 1:30, verbose = FALSE)
> macropahge.integrated <- FindClusters(macropahge.integrated, verbose = FALSE,resolution = 2)
> 
> DimPlot(macropahge.integrated, reduction = "umap",group.by = "seurat_clusters",label = TRUE)
> DimPlot(macropahge.integrated, reduction = "umap",group.by = "orig.ident",label = TRUE)
> 
> **#2 extract original UMI matrix and SCtransform ,batch correction.**
> DefaultAssay(macropahge) <- "RNA"
> 
> macropahge.list <- SplitObject(macropahge, split.by = "orig.ident")
> 
> for (i in 1:length(x = macropahge.list)){
> macropahge.list[[i]] <- SCTransform(object = macropahge.list[[i]],verbose = FALSE,return.only.var.genes = FALSE)}
> 
> macropahge.features <- SelectIntegrationFeatures(object.list = macropahge.list, nfeatures = 3000)
> macropahge.list <- PrepSCTIntegration(object.list = macropahge.list, anchor.features = macropahge.features)
> 
> reference_dataset <- which(names(macropahge.list) == "SC33")
> 
> macropahge.anchors <- FindIntegrationAnchors(object.list = macropahge.list, normalization.method = "SCT", k.filter = 13, k.score = 12,dims = 1:10, anchor.features = macropahge.features, reference = reference_dataset)
> 
> macropahge.integrated <- IntegrateData(anchorset = macropahge.anchors, normalization.method = "SCT",k.weight = 50)
> 
> macropahge.integrated <- RunPCA(object = macropahge.integrated, verbose = FALSE)
> macropahge.integrated <- RunUMAP(object = macropahge.integrated, dims = 1:30)
> 
> macropahge.integrated <- FindNeighbors(macropahge.integrated, dims = 1:30, verbose = FALSE)
> macropahge.integrated <- FindClusters(macropahge.integrated, verbose = FALSE,resolution = 1.2)
> 
> DimPlot(macropahge, reduction = "umap",group.by = "seurat_clusters",label = TRUE) + NoLegend()
> DimPlot(macropahge, reduction = "umap",group.by = "orig.ident",label = TRUE)
> 
> In this approach, cells in some samples are very low, around 10 to 30 cells. So I set very low k.filter = 13 and k.score = 12.
> 
> **#3 Processing as a single sample. Don't consider the batch effect.**
> DefaultAssay(macropahge) <- "RNA"
> macropahge <- NormalizeData(macropahge)
> macropahge <- FindVariableFeatures(macropahge, selection.method = "vst", nfeatures = 2000)
> all.genes <- rownames(macropahge)
> macropahge <- ScaleData(macropahge, features = all.genes)
> macropahge <- RunPCA(macropahge, features = VariableFeatures(object = macropahge))
> macropahge <- RunUMAP(macropahge, dims = 1:10)
> macropahge <- FindNeighbors(macropahge, dims = 1:10)
> macropahge <- FindClusters(macropahge, resolution = 0.8)
> 
> DimPlot(macropahge, reduction = "umap",group.by = "seurat_clusters",label = TRUE) + NoLegend()
> DimPlot(macropahge, reduction = "umap",group.by = "orig.ident",label = TRUE)
> 
> 3 methods can work, but I am not sure which method is right.
> looking forward to your help~
> 
> Thanks.

Hi,
I am also curious about this question, have you decided which one is more suitable? Hope you can share me with some suggestion!

Best,
Wei

**Comment by vertesy** [comment]
Hey Wei, this is [not the Seurat repo](https://github.com/satijalab/seurat ). This is package I wrote, mostly useful for Seurat 2.
