### ISSUE TITLE
Support For Seurat 4.X

### ISSUE THREAD

**Issue by akhst7** [vertesy/Seurat.multicore#7]
HI, 

I appreciate if you could support multicore for Seurat v.4.x 

Thanks.

**Comment by vertesy** [comment]
Hey, Seurat v3 and later can do multi core by default, did you try that?

**Comment by akhst7** [comment]
@vertesy 

I used `future` to run limited selection of Seurat commands but it did not run.  V3.0 works fine with future but not 4..0
