### ISSUE TITLE
How to filtrate the best, scRNA seq 

### ISSUE THREAD

**Issue by Labyadh** [vertesy/Seurat.multicore#8]
![199](https://github.com/vertesy/Seurat.multicore/assets/137498045/f1f4a3bd-c200-4967-8616-072d064b633a)
![S001D3A2022](https://github.com/vertesy/Seurat.multicore/assets/137498045/d09029f2-910f-4237-8acb-7770b8528775)
![S199TET22022](https://github.com/vertesy/Seurat.multicore/assets/137498045/b2295ab8-a6f9-4f35-8f63-eab41dc36a43)
Hello everyone,
I would like to know your opinion on the filtration of three samples. Samples S001D3A2022 and S199TET22022 are combinations of coculture between mesenchymal cells and leukemic cells whereas sample 199 only represents mesenchymal cells. As you can see from the violin plot, the detection of genes and UMIs is heterogeneous. For each sample, I noted the presence of two populations: a population at the bottom with low UMIs and features and a population at the top which expresses more genes.
I'm not sure whether to eliminate the  population at the bottom or not. What do you think? Thank you very much for your reply.

**Comment by vertesy** [comment]
Hi Mayssa, this library is not maintained, and unfortunately as single person giving analysis advice is anyways beyond what I can manage. 
A solution in this case is a sample- or better, cell-type-based filtering thresholds. You can get that by first analyzing your data with very minimal filtering to define cell types, then define thresholds for each, eg. based on median nFeautre per cell type.
